package br.gms.siscofa.model.simplificado;
// Generated 29/06/2017 17:32:00 by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Configuracao generated by hbm2java
 */
@Entity
@Table(name = "Configuracao", catalog = "siscofa")
public class Configuracao implements java.io.Serializable {

	private Integer id;
	private Date dtUltimaSincronizacao;
	private Integer idApp;
	private Integer usuario;

	public Configuracao() {
	}

	public Configuracao(Date dtUltimaSincronizacao, Integer idApp, Integer usuario) {
		this.dtUltimaSincronizacao = dtUltimaSincronizacao;
		this.idApp = idApp;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_ultima_sincronizacao", length = 19)
	public Date getDtUltimaSincronizacao() {
		return this.dtUltimaSincronizacao;
	}

	public void setDtUltimaSincronizacao(Date dtUltimaSincronizacao) {
		this.dtUltimaSincronizacao = dtUltimaSincronizacao;
	}

	@Column(name = "id_app")
	public Integer getIdApp() {
		return this.idApp;
	}

	public void setIdApp(Integer idApp) {
		this.idApp = idApp;
	}

	@Column(name = "usuario")
	public Integer getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Integer usuario) {
		this.usuario = usuario;
	}

}
