package br.gms.siscofa.model.simplificado;
// Generated 29/06/2017 17:32:00 by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoMovimentacao generated by hbm2java
 */
@Entity
@Table(name = "tipo_movimentacao", catalog = "siscofa")
public class TipoMovimentacao implements java.io.Serializable {

	private Integer id;
	private String descricao;

	public TipoMovimentacao() {
	}

	public TipoMovimentacao(String descricao) {
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
